.TH "AbstractAlgorithm" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractAlgorithm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <templateMethod\&.h>\fP
.PP
Inherited by \fBConcreteAlgorithm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperation\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdoOperation1\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdoOperation2\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdoOperation3\fP ()=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void AbstractAlgorithm::doOperation1 ()\fC [protected]\fP, \fC [pure virtual]\fP"

.SS "virtual void AbstractAlgorithm::doOperation2 ()\fC [protected]\fP, \fC [pure virtual]\fP"

.SS "virtual void AbstractAlgorithm::doOperation3 ()\fC [protected]\fP, \fC [pure virtual]\fP"

.SS "void AbstractAlgorithm::operation ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
