.TH "F:/Projects/sandbox/src/boost/chromaaberration.h" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/boost/chromaaberration.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBint_p_NULL\fP   (int*)NULL"
.br
.ti -1c
.RI "#define \fBpng_infopp_NULL\fP   (png_infopp)NULL"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define int_p_NULL   (int*)NULL"

.SS "#define png_infopp_NULL   (png_infopp)NULL"

.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
