.TH "F:/Projects/sandbox/src/boost/chromaaberration.cpp" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/boost/chromaaberration.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chromaaberration\&.h'\fP
.br
\fC#include <boost/gil/extension/io/png_io\&.hpp>\fP
.br
\fC#include <boost/gil/image\&.hpp>\fP
.br
\fC#include <boost/gil/image_view\&.hpp>\fP
.br
\fC#include <random>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename ImageView > void \fBcolorAberration\fP (ImageView source, ImageView destination)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename ImageView > void colorAberration (ImageViewsource, ImageViewdestination)\fC [inline]\fP"

.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
