.TH "ConcreteAlgorithm" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConcreteAlgorithm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <templateMethod\&.h>\fP
.PP
Inherits \fBAbstractAlgorithm\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
