.TH "F:/Projects/sandbox/src/main.cpp" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <random>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'shed\&.h'\fP
.br
\fC#include 'pattern/singleton\&.h'\fP
.br
\fC#include 'quicksort\&.h'\fP
.br
\fC#include 'options\&.h'\fP
.br
\fC#include 'variant\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
