.TH "F:/Projects/sandbox/src/quicksort.h" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/quicksort.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include 'shed\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBsandbox\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Iterator > void \fBsandbox::printOut\fP (Iterator front, Iterator back)"
.br
.ti -1c
.RI "template<typename Iterator > void \fBsandbox::quickSort\fP (Iterator front, Iterator back)"
.br
.ti -1c
.RI "template<typename T > std::vector< T > & \fBsandbox::quickSort\fP (std::vector< T > &sortable)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
