.TH "sandbox::pattern::DrawTool" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sandbox::pattern::DrawTool \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <state\&.h>\fP
.PP
Inherits \fBsandbox::pattern::Tool\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonMouseDown\fP (\fBToolController\fP *controller)"
.br
.ti -1c
.RI "void \fBonMouseUp\fP (\fBToolController\fP *controller)"
.br
.ti -1c
.RI "void \fBonMouseMove\fP (\fBToolController\fP *controller)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void sandbox::pattern::DrawTool::onMouseDown (\fBToolController\fP *controller)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBsandbox::pattern::Tool\fP\&.
.SS "void sandbox::pattern::DrawTool::onMouseMove (\fBToolController\fP *controller)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBsandbox::pattern::Tool\fP\&.
.SS "void sandbox::pattern::DrawTool::onMouseUp (\fBToolController\fP *controller)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBsandbox::pattern::Tool\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
