.TH "sandbox::pattern::Singleton" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sandbox::pattern::Singleton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <singleton\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBdoMagic\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSingleton\fP * \fBinstance\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int sandbox::pattern::Singleton::doMagic ()\fC [inline]\fP"

.SS "static \fBSingleton\fP* sandbox::pattern::Singleton::instance ()\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
