.TH "sandbox::pattern::ToolController" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sandbox::pattern::ToolController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <state\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonMouseDown\fP ()"
.br
.ti -1c
.RI "void \fBonMouseUp\fP ()"
.br
.ti -1c
.RI "void \fBonMouseMove\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTool\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void sandbox::pattern::ToolController::onMouseDown ()\fC [inline]\fP"

.SS "void sandbox::pattern::ToolController::onMouseMove ()\fC [inline]\fP"

.SS "void sandbox::pattern::ToolController::onMouseUp ()\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTool\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
