.TH "sandbox::TimeType" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sandbox::TimeType \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timetype\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeType\fP (const int hour, const int minute)"
.br
.ti -1c
.RI "double \fBgetDegree\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sandbox::TimeType::TimeType (const inthour, const intminute)"

.SH "Member Function Documentation"
.PP 
.SS "double sandbox::TimeType::getDegree () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
