.TH "F:/Projects/sandbox/src/pattern/state.h" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/pattern/state.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsandbox::pattern::Tool\fP"
.br
.ti -1c
.RI "class \fBsandbox::pattern::DrawTool\fP"
.br
.ti -1c
.RI "class \fBsandbox::pattern::StateSelect\fP"
.br
.ti -1c
.RI "class \fBsandbox::pattern::ToolController\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBsandbox\fP"
.br
.ti -1c
.RI "\fBsandbox::pattern\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
