.TH "F:/Projects/sandbox/src/pattern/templateMethod.h" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/pattern/templateMethod.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractAlgorithm\fP"
.br
.ti -1c
.RI "class \fBConcreteAlgorithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
