.TH "F:/Projects/sandbox/src/variant.h" 3 "Tue Oct 29 2013" "sandbox" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Projects/sandbox/src/variant.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <istream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsandbox::Variant\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBsandbox\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBsandbox::operator<<\fP (std::ostream &output, Variant const &variant)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for sandbox from the source code\&.
